[Source]
Type=url-file
Path=https://github.com/alyraffauf/kyanite/releases/download/sysext-rocm
MatchPattern=rocm-@v-x86-64.raw

[Target]
Type=regular-file
Path=/var/lib/extensions
MatchPattern=rocm-@v-x86-64.raw
CurrentSymlinkPath=/var/lib/extensions/rocm.raw
