---
name: Build Images
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
        paths-ignore:
            - "**/README.md"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-kyanite:
        name: Build kyanite
        uses: ./.github/workflows/reusable_build.yml
        secrets: inherit
        permissions:
            contents: read
            packages: write
            id-token: write
        with:
            image_name: "kyanite"
            image_flavor: "main"
            image_desc: "Kyanite - A clean KDE Plasma bootc image"
            image_keywords: "bootc,ublue,universal-blue,kde"
